# Generated by Django 2.2.7 on 2019-11-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('run', models.CharField(max_length=9, unique=True)),
                ('correo', models.CharField(max_length=20)),
                ('comentarios', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionOrigen', models.CharField(max_length=100)),
                ('comunaDestino', models.CharField(max_length=50)),
                ('direccionDestino', models.CharField(max_length=100)),
                ('comunaOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renta.Persona')),
            ],
        ),
    ]
