# Generated by Django 2.2.7 on 2019-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0003_auto_20191117_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirDestino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunaDestino', models.CharField(max_length=50)),
                ('direccionDestino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DirOrigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunaOrigen', models.CharField(max_length=50)),
                ('direccionOrigen', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.AlterField(
            model_name='persona',
            name='run',
            field=models.IntegerField(unique=True),
        ),
    ]
